name: Run Selenium Script Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
      
    - name: Install ChromeDriver
      run: |
        CHROME_DRIVER_VERSION="115.0.5790.171" 
        wget "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        mv chromedriver /usr/local/bin/
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
      
    - name: Run Selenium script
      run: python path/to/your/script.py  # Adjust the path to your script
